# [other_build_script]={phonenumber_build}

[dependencies]

[package]
  cjc-version = "0.51.4"
  compile-option = "-O2"
  description = "nothing here"
  link-option = ""
  name = "phonenumber4cj"
  output-type = "dynamic"
  src-dir = "src"
  target-dir = ""
  version = "0.0.5"
  package-configuration = {}
