/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2022-2024. All rights resvered.
 */

package phonenumber4cj.libphonenumber.metadata

internal import std.sync.*
internal import encoding.json.*
internal import std.fs.*
internal import std.os.*
internal import std.os.posix.*
internal import phonenumber4cj.libphonenumber.data.*
internal import std.collection.*
internal import phonenumber4cj.libphonenumber.inter.*
internal import std.io.*
internal import std.regex.*
internal import phonenumber4cj.libphonenumber.internal.*