/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2022-2024. All rights resvered.
 */

package cangjie_tpc::phonenumber4cj.libphonenumber.inter

public class CountryCodeToRegionCodeMap {

    public static func getCountryCodeToRegionCodeMap(): HashMap<Int32, ArrayList<String>> {

        var countryCodeToRegionCodeMap: HashMap<Int32, ArrayList<String>> = HashMap<Int32, ArrayList<String>>(286)
        var listWithRegionCode: ArrayList<String> = ArrayList<String>(25)

        listWithRegionCode.add("US")
        listWithRegionCode.add("AG")
        listWithRegionCode.add("AI")
        listWithRegionCode.add("AS")
        listWithRegionCode.add("BB")
        listWithRegionCode.add("BM")
        listWithRegionCode.add("BS")
        listWithRegionCode.add("CA")
        listWithRegionCode.add("DM")
        listWithRegionCode.add("DO")
        listWithRegionCode.add("GD")
        listWithRegionCode.add("GU")
        listWithRegionCode.add("JM")
        listWithRegionCode.add("KN")
        listWithRegionCode.add("KY")
        listWithRegionCode.add("LC")
        listWithRegionCode.add("MP")
        listWithRegionCode.add("MS")
        listWithRegionCode.add("PR")
        listWithRegionCode.add("SX")
        listWithRegionCode.add("TC")
        listWithRegionCode.add("TT")
        listWithRegionCode.add("VC")
        listWithRegionCode.add("VG")
        listWithRegionCode.add("VI")
        countryCodeToRegionCodeMap.add(1, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(2)
        listWithRegionCode.add("RU")
        listWithRegionCode.add("KZ")
        countryCodeToRegionCodeMap.add(7, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("EG")
        countryCodeToRegionCodeMap.add(20, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("ZA")
        countryCodeToRegionCodeMap.add(27, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("GR")
        countryCodeToRegionCodeMap.add(30, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("NL")
        countryCodeToRegionCodeMap.add(31, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BE")
        countryCodeToRegionCodeMap.add(32, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("FR")
        countryCodeToRegionCodeMap.add(33, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("ES")
        countryCodeToRegionCodeMap.add(34, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("HU")
        countryCodeToRegionCodeMap.add(36, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(2)
        listWithRegionCode.add("IT")
        listWithRegionCode.add("VA")
        countryCodeToRegionCodeMap.add(39, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("RO")
        countryCodeToRegionCodeMap.add(40, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CH")
        countryCodeToRegionCodeMap.add(41, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("AT")
        countryCodeToRegionCodeMap.add(43, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(4)
        listWithRegionCode.add("GB")
        listWithRegionCode.add("GG")
        listWithRegionCode.add("IM")
        listWithRegionCode.add("JE")
        countryCodeToRegionCodeMap.add(44, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("DK")
        countryCodeToRegionCodeMap.add(45, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SE")
        countryCodeToRegionCodeMap.add(46, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(2)
        listWithRegionCode.add("NO")
        listWithRegionCode.add("SJ")
        countryCodeToRegionCodeMap.add(47, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("PL")
        countryCodeToRegionCodeMap.add(48, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("DE")
        countryCodeToRegionCodeMap.add(49, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("PE")
        countryCodeToRegionCodeMap.add(51, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MX")
        countryCodeToRegionCodeMap.add(52, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CU")
        countryCodeToRegionCodeMap.add(53, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("AR")
        countryCodeToRegionCodeMap.add(54, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BR")
        countryCodeToRegionCodeMap.add(55, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CL")
        countryCodeToRegionCodeMap.add(56, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CO")
        countryCodeToRegionCodeMap.add(57, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("VE")
        countryCodeToRegionCodeMap.add(58, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MY")
        countryCodeToRegionCodeMap.add(60, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(3)
        listWithRegionCode.add("AU")
        listWithRegionCode.add("CC")
        listWithRegionCode.add("CX")
        countryCodeToRegionCodeMap.add(61, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("ID")
        countryCodeToRegionCodeMap.add(62, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("PH")
        countryCodeToRegionCodeMap.add(63, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("NZ")
        countryCodeToRegionCodeMap.add(64, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SG")
        countryCodeToRegionCodeMap.add(65, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("TH")
        countryCodeToRegionCodeMap.add(66, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("JP")
        countryCodeToRegionCodeMap.add(81, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("KR")
        countryCodeToRegionCodeMap.add(82, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("VN")
        countryCodeToRegionCodeMap.add(84, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CN")
        countryCodeToRegionCodeMap.add(86, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("TR")
        countryCodeToRegionCodeMap.add(90, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("IN")
        countryCodeToRegionCodeMap.add(91, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("PK")
        countryCodeToRegionCodeMap.add(92, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("AF")
        countryCodeToRegionCodeMap.add(93, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("LK")
        countryCodeToRegionCodeMap.add(94, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MM")
        countryCodeToRegionCodeMap.add(95, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("IR")
        countryCodeToRegionCodeMap.add(98, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SS")
        countryCodeToRegionCodeMap.add(211, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(2)
        listWithRegionCode.add("MA")
        listWithRegionCode.add("EH")
        countryCodeToRegionCodeMap.add(212, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("DZ")
        countryCodeToRegionCodeMap.add(213, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("TN")
        countryCodeToRegionCodeMap.add(216, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("LY")
        countryCodeToRegionCodeMap.add(218, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("GM")
        countryCodeToRegionCodeMap.add(220, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SN")
        countryCodeToRegionCodeMap.add(221, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MR")
        countryCodeToRegionCodeMap.add(222, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("ML")
        countryCodeToRegionCodeMap.add(223, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("GN")
        countryCodeToRegionCodeMap.add(224, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CI")
        countryCodeToRegionCodeMap.add(225, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BF")
        countryCodeToRegionCodeMap.add(226, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("NE")
        countryCodeToRegionCodeMap.add(227, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("TG")
        countryCodeToRegionCodeMap.add(228, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BJ")
        countryCodeToRegionCodeMap.add(229, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MU")
        countryCodeToRegionCodeMap.add(230, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("LR")
        countryCodeToRegionCodeMap.add(231, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SL")
        countryCodeToRegionCodeMap.add(232, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("GH")
        countryCodeToRegionCodeMap.add(233, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("NG")
        countryCodeToRegionCodeMap.add(234, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("TD")
        countryCodeToRegionCodeMap.add(235, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CF")
        countryCodeToRegionCodeMap.add(236, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CM")
        countryCodeToRegionCodeMap.add(237, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CV")
        countryCodeToRegionCodeMap.add(238, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("ST")
        countryCodeToRegionCodeMap.add(239, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("GQ")
        countryCodeToRegionCodeMap.add(240, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("GA")
        countryCodeToRegionCodeMap.add(241, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CG")
        countryCodeToRegionCodeMap.add(242, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CD")
        countryCodeToRegionCodeMap.add(243, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("AO")
        countryCodeToRegionCodeMap.add(244, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("GW")
        countryCodeToRegionCodeMap.add(245, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("IO")
        countryCodeToRegionCodeMap.add(246, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("AC")
        countryCodeToRegionCodeMap.add(247, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SC")
        countryCodeToRegionCodeMap.add(248, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SD")
        countryCodeToRegionCodeMap.add(249, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("RW")
        countryCodeToRegionCodeMap.add(250, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("ET")
        countryCodeToRegionCodeMap.add(251, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SO")
        countryCodeToRegionCodeMap.add(252, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("DJ")
        countryCodeToRegionCodeMap.add(253, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("KE")
        countryCodeToRegionCodeMap.add(254, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("TZ")
        countryCodeToRegionCodeMap.add(255, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("UG")
        countryCodeToRegionCodeMap.add(256, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BI")
        countryCodeToRegionCodeMap.add(257, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MZ")
        countryCodeToRegionCodeMap.add(258, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("ZM")
        countryCodeToRegionCodeMap.add(260, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MG")
        countryCodeToRegionCodeMap.add(261, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(2)
        listWithRegionCode.add("RE")
        listWithRegionCode.add("YT")
        countryCodeToRegionCodeMap.add(262, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("ZW")
        countryCodeToRegionCodeMap.add(263, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("NA")
        countryCodeToRegionCodeMap.add(264, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MW")
        countryCodeToRegionCodeMap.add(265, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("LS")
        countryCodeToRegionCodeMap.add(266, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BW")
        countryCodeToRegionCodeMap.add(267, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SZ")
        countryCodeToRegionCodeMap.add(268, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("KM")
        countryCodeToRegionCodeMap.add(269, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(2)
        listWithRegionCode.add("SH")
        listWithRegionCode.add("TA")
        countryCodeToRegionCodeMap.add(290, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("ER")
        countryCodeToRegionCodeMap.add(291, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("AW")
        countryCodeToRegionCodeMap.add(297, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("FO")
        countryCodeToRegionCodeMap.add(298, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("GL")
        countryCodeToRegionCodeMap.add(299, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("GI")
        countryCodeToRegionCodeMap.add(350, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("PT")
        countryCodeToRegionCodeMap.add(351, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("LU")
        countryCodeToRegionCodeMap.add(352, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("IE")
        countryCodeToRegionCodeMap.add(353, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("IS")
        countryCodeToRegionCodeMap.add(354, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("AL")
        countryCodeToRegionCodeMap.add(355, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MT")
        countryCodeToRegionCodeMap.add(356, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CY")
        countryCodeToRegionCodeMap.add(357, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(2)
        listWithRegionCode.add("FI")
        listWithRegionCode.add("AX")
        countryCodeToRegionCodeMap.add(358, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BG")
        countryCodeToRegionCodeMap.add(359, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("LT")
        countryCodeToRegionCodeMap.add(370, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("LV")
        countryCodeToRegionCodeMap.add(371, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("EE")
        countryCodeToRegionCodeMap.add(372, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MD")
        countryCodeToRegionCodeMap.add(373, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("AM")
        countryCodeToRegionCodeMap.add(374, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BY")
        countryCodeToRegionCodeMap.add(375, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("AD")
        countryCodeToRegionCodeMap.add(376, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MC")
        countryCodeToRegionCodeMap.add(377, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SM")
        countryCodeToRegionCodeMap.add(378, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("UA")
        countryCodeToRegionCodeMap.add(380, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("RS")
        countryCodeToRegionCodeMap.add(381, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("ME")
        countryCodeToRegionCodeMap.add(382, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("XK")
        countryCodeToRegionCodeMap.add(383, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("HR")
        countryCodeToRegionCodeMap.add(385, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SI")
        countryCodeToRegionCodeMap.add(386, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BA")
        countryCodeToRegionCodeMap.add(387, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MK")
        countryCodeToRegionCodeMap.add(389, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CZ")
        countryCodeToRegionCodeMap.add(420, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SK")
        countryCodeToRegionCodeMap.add(421, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("LI")
        countryCodeToRegionCodeMap.add(423, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("FK")
        countryCodeToRegionCodeMap.add(500, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BZ")
        countryCodeToRegionCodeMap.add(501, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("GT")
        countryCodeToRegionCodeMap.add(502, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SV")
        countryCodeToRegionCodeMap.add(503, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("HN")
        countryCodeToRegionCodeMap.add(504, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("NI")
        countryCodeToRegionCodeMap.add(505, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CR")
        countryCodeToRegionCodeMap.add(506, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("PA")
        countryCodeToRegionCodeMap.add(507, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("PM")
        countryCodeToRegionCodeMap.add(508, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("HT")
        countryCodeToRegionCodeMap.add(509, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(3)
        listWithRegionCode.add("GP")
        listWithRegionCode.add("BL")
        listWithRegionCode.add("MF")
        countryCodeToRegionCodeMap.add(590, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BO")
        countryCodeToRegionCodeMap.add(591, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("GY")
        countryCodeToRegionCodeMap.add(592, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("EC")
        countryCodeToRegionCodeMap.add(593, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("GF")
        countryCodeToRegionCodeMap.add(594, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("PY")
        countryCodeToRegionCodeMap.add(595, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MQ")
        countryCodeToRegionCodeMap.add(596, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SR")
        countryCodeToRegionCodeMap.add(597, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("UY")
        countryCodeToRegionCodeMap.add(598, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(2)
        listWithRegionCode.add("CW")
        listWithRegionCode.add("BQ")
        countryCodeToRegionCodeMap.add(599, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("TL")
        countryCodeToRegionCodeMap.add(670, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("NF")
        countryCodeToRegionCodeMap.add(672, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BN")
        countryCodeToRegionCodeMap.add(673, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("NR")
        countryCodeToRegionCodeMap.add(674, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("PG")
        countryCodeToRegionCodeMap.add(675, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("TO")
        countryCodeToRegionCodeMap.add(676, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SB")
        countryCodeToRegionCodeMap.add(677, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("VU")
        countryCodeToRegionCodeMap.add(678, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("FJ")
        countryCodeToRegionCodeMap.add(679, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("PW")
        countryCodeToRegionCodeMap.add(680, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("WF")
        countryCodeToRegionCodeMap.add(681, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("CK")
        countryCodeToRegionCodeMap.add(682, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("NU")
        countryCodeToRegionCodeMap.add(683, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("WS")
        countryCodeToRegionCodeMap.add(685, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("KI")
        countryCodeToRegionCodeMap.add(686, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("NC")
        countryCodeToRegionCodeMap.add(687, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("TV")
        countryCodeToRegionCodeMap.add(688, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("PF")
        countryCodeToRegionCodeMap.add(689, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("TK")
        countryCodeToRegionCodeMap.add(690, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("FM")
        countryCodeToRegionCodeMap.add(691, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MH")
        countryCodeToRegionCodeMap.add(692, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("001")
        countryCodeToRegionCodeMap.add(800, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("001")
        countryCodeToRegionCodeMap.add(808, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("KP")
        countryCodeToRegionCodeMap.add(850, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("HK")
        countryCodeToRegionCodeMap.add(852, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MO")
        countryCodeToRegionCodeMap.add(853, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("KH")
        countryCodeToRegionCodeMap.add(855, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("LA")
        countryCodeToRegionCodeMap.add(856, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("001")
        countryCodeToRegionCodeMap.add(870, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("001")
        countryCodeToRegionCodeMap.add(878, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BD")
        countryCodeToRegionCodeMap.add(880, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("001")
        countryCodeToRegionCodeMap.add(881, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("001")
        countryCodeToRegionCodeMap.add(882, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("001")
        countryCodeToRegionCodeMap.add(883, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("TW")
        countryCodeToRegionCodeMap.add(886, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("001")
        countryCodeToRegionCodeMap.add(888, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MV")
        countryCodeToRegionCodeMap.add(960, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("LB")
        countryCodeToRegionCodeMap.add(961, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("JO")
        countryCodeToRegionCodeMap.add(962, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SY")
        countryCodeToRegionCodeMap.add(963, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("IQ")
        countryCodeToRegionCodeMap.add(964, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("KW")
        countryCodeToRegionCodeMap.add(965, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("SA")
        countryCodeToRegionCodeMap.add(966, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("YE")
        countryCodeToRegionCodeMap.add(967, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("OM")
        countryCodeToRegionCodeMap.add(968, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("PS")
        countryCodeToRegionCodeMap.add(970, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("AE")
        countryCodeToRegionCodeMap.add(971, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("IL")
        countryCodeToRegionCodeMap.add(972, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BH")
        countryCodeToRegionCodeMap.add(973, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("QA")
        countryCodeToRegionCodeMap.add(974, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("BT")
        countryCodeToRegionCodeMap.add(975, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("MN")
        countryCodeToRegionCodeMap.add(976, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("NP")
        countryCodeToRegionCodeMap.add(977, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("001")
        countryCodeToRegionCodeMap.add(979, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("TJ")
        countryCodeToRegionCodeMap.add(992, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("TM")
        countryCodeToRegionCodeMap.add(993, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("AZ")
        countryCodeToRegionCodeMap.add(994, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("GE")
        countryCodeToRegionCodeMap.add(995, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("KG")
        countryCodeToRegionCodeMap.add(996, listWithRegionCode)

        listWithRegionCode = ArrayList<String>(1)
        listWithRegionCode.add("UZ")
        countryCodeToRegionCodeMap.add(998, listWithRegionCode)

        return countryCodeToRegionCodeMap
    }
}
