/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2022-2024. All rights resvered.
 */

package prefixmapper

struct PrefixReaderFilePath {
    public static let RESOURCES: String = "resources"
    public static let US: String = "1"
    public static let ZH: String = "86"
    public static let TZ: String = "tz"
    public static let CARRIER_US_EN: String = "1_en_carrier.txt"
    public static let CARRIER_ZH_EN: String = "86_en_carrier.txt"
    public static let CARRIER_ZH_CN: String = "86_zh_carrier.txt"
    public static let GEO_US_EN: String = "1_en_geo.txt"
    public static let GEO_ZH_EN: String = "86_en_geo.txt"
    public static let GEO_ZH_CN: String = "86_zh_geo.txt"
    public static let TZ_ALL: String = "map_data.txt"
}
