/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2022-2024. All rights resvered.
 */

package phonenumber4cj.libphonenumber

internal import std.math.*
internal import std.collection.*
internal import std.unicode.*
internal import std.io.*
internal import std.regex.*
internal import std.sync.*
internal import log.*
internal import std.sort.SortExtension
internal import std.convert.Parsable
internal import phonenumber4cj.libphonenumber.internal.*
internal import phonenumber4cj.libphonenumber.metadata.*
internal import phonenumber4cj.libphonenumber.inter.*